package com.rprescott.dndtool.server.database.login;

/**
 * Class representing the credentials of a user.
 */
public class CredentialDTO {

    /** Autogenerated ID from the database. */ 
    private long id;
    /** The user name. */
    private String userName;
    /** Salt generated at account registration. */
    private byte[] salt;
    /** The hashed password. */
    private String hash;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public byte[] getSalt() {
        return salt;
    }

    public void setSalt(byte[] salt) {
        this.salt = salt;
    }

    public String getHash() {
        return hash;
    }

    public void setHash(String hash) {
        this.hash = hash;
    }

}
