package com.dndtool.model;

import java.util.List;

/**
 * Class representing a user.
 */
public class UserDTO {
    
    /** Autogenerated ID from the database. */
    private long id;
    /** The user name. */
    private String userName;
    /** The characters the user has created. */
    private List<CharacterDTO> characters;
    /** The IV for the cipher used to mangle the verification secret and salt. */
    private byte[] cipherIv;
    /** The hashed secret used for verification. */
    private byte[] cipheredVerificationSecret;
    /** The hashed salt used for verification. */
    private byte[] cipheredVerificationSalt;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public List<CharacterDTO> getCharacters() {
        return characters;
    }

    public void setCharacters(List<CharacterDTO> characters) {
        this.characters = characters;
    }

    public byte[] getCipherIv() {
        return cipherIv;
    }

    public void setCipherIv(byte[] cipherIv) {
        this.cipherIv = cipherIv;
    }

    public byte[] getCipheredVerificationSecret() {
        return cipheredVerificationSecret;
    }

    public void setCipheredVerificationSecret(byte[] cipheredVerificationSecret) {
        this.cipheredVerificationSecret = cipheredVerificationSecret;
    }

    public byte[] getCipheredVerificationSalt() {
        return cipheredVerificationSalt;
    }

    public void setCipheredVerificationSalt(byte[] cipheredVerificationSalt) {
        this.cipheredVerificationSalt = cipheredVerificationSalt;
    }
}
